import 'dotenv/config'
import { PrismaClient } from '../src/generated/prisma'
import { PrismaNeon } from '@prisma/adapter-neon'
import { Pool } from '@neondatabase/serverless'

const adapter = new PrismaNeon(
    new Pool({
        connectionString: process.env.DATABASE_URL!,
    }),
)
const prisma = new PrismaClient({ adapter } as any)

async function main() {
    console.log('🌱 Starting seed...')

    // -----------------------------
    // 1. Clean database
    // -----------------------------
    // IMPORTANTE: Los nombres deben coincidir con tu schema.prisma
    await prisma.games.deleteMany()
    await prisma.console.deleteMany()

    console.log('🧹 Database cleaned')

    // -----------------------------
    // 2. Create Consoles
    // -----------------------------
    await prisma.console.createMany({
        data: [
            {
                name: 'PlayStation 5',
                manufacturer: 'Sony Interactive Entertainment',
                releaseDate: new Date('2020-11-12'), // Corregido camelCase del schema
                description: 'The PlayStation 5 (PS5) is a home video game console bringing 4K gaming at 120Hz and ray tracing support.',
            },
            {
                name: 'Xbox Series X',
                manufacturer: 'Microsoft',
                releaseDate: new Date('2020-11-10'),
                description: 'The Xbox Series X is a high-performance console, featuring a custom AMD processor and 12 TFLOPS of graphical power.',
            },
            {
                name: 'Nintendo Switch OLED Model',
                manufacturer: 'Nintendo',
                releaseDate: new Date('2021-10-08'),
                description: 'A hybrid console that can be used as a home console and a portable handheld device, now with a vibrant OLED screen.',
            },
            {
                name: 'Nintendo Switch 2',
                manufacturer: 'Nintendo',
                releaseDate: new Date('2025-06-05'),
                description: 'The successor to the popular Nintendo Switch, featuring larger magnetic Joy-cons and enhanced performance.',
            },
            {
                name: 'Steam Deck OLED',
                manufacturer: 'Valve',
                releaseDate: new Date('2023-11-16'),
                description: 'A powerful handheld gaming computer that plays PC games from your Steam library on the go.',
            },
        ],
    })

    console.log('🎮 5 consoles seeded')

    // -----------------------------
    // 3. Get consoles from DB
    // -----------------------------
    const allConsoles = await prisma.console.findMany()

    const ps5 = allConsoles.find(c => c.name === 'PlayStation 5')
    const xbox = allConsoles.find(c => c.name === 'Xbox Series X')
    const switchOLED = allConsoles.find(c => c.name === 'Nintendo Switch OLED Model')
    const switch2 = allConsoles.find(c => c.name === 'Nintendo Switch 2')
    const steamDeck = allConsoles.find(c => c.name === 'Steam Deck OLED')

    // -----------------------------
    // 4. Create Games
    // -----------------------------
    const gamesData = [
        {
            title: 'God of War Ragnarök',
            developer: 'Santa Monica Studio',
            releaseDate: new Date('2022-11-09'), // Corregido a releaseDate (D mayúscula)
            price: 69.99,
            genre: 'Action-adventure',
            description: 'Kratos and Atreus must journey to each of the Nine Realms and find answers as the forces of Asgard prepare for a prophesied battle.',
            console_id: ps5?.id || 0,
        },
        {
            title: 'Halo Infinite',
            developer: '343 Industries',
            releaseDate: new Date('2021-12-08'),
            price: 59.99,
            genre: 'First-person shooter',
            description: 'Master Chief returns in the most expansive Halo campaign yet.',
            console_id: xbox?.id || 0,
        },
        {
            title: 'The Legend of Zelda: Tears of the Kingdom',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2023-05-12'),
            price: 69.99,
            genre: 'Action-adventure',
            description: 'Link soars through the skies and explores new areas of Hyrule.',
            console_id: switchOLED?.id || 0,
        },
        {
            title: 'Elden Ring',
            developer: 'FromSoftware',
            releaseDate: new Date('2022-02-25'),
            price: 59.99,
            genre: 'Action role-playing',
            description: 'A fantasy action RPG adventure set within a world created by Hidetaka Miyazaki.',
            console_id: ps5?.id || 0,
        },
        {
            title: 'Forza Horizon 5',
            developer: 'Playground Games',
            releaseDate: new Date('2021-11-09'),
            price: 59.99,
            genre: 'Racing',
            description: 'Explore the vibrant open world landscapes of Mexico.',
            console_id: xbox?.id || 0,
        },
        {
            title: 'Pokémon Scarlet',
            developer: 'Game Freak',
            releaseDate: new Date('2022-11-18'),
            price: 59.99,
            genre: 'Role-playing',
            description: 'Embark on a new journey in the Paldea region.',
            console_id: switchOLED?.id || 0,
        },
        {
            title: 'Spider-Man 2',
            developer: 'Insomniac Games',
            releaseDate: new Date('2023-10-20'),
            price: 69.99,
            genre: 'Action-adventure',
            description: 'Peter Parker and Miles Morales face the Symbiote threat.',
            console_id: ps5?.id || 0,
        },
        {
            title: 'Starfield',
            developer: 'Bethesda Game Studios',
            releaseDate: new Date('2023-09-06'),
            price: 69.99,
            genre: 'Role-playing',
            description: 'Explore the vastness of space and create your own story.',
            console_id: xbox?.id || 0,
        },
        {
            title: 'Mario Kart 9',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2025-12-01'),
            price: 59.99,
            genre: 'Racing',
            description: 'The next installment in the popular Mario Kart series.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Metroid Prime 4: Beyond',
            developer: 'Retro Studios',
            releaseDate: new Date('2025-10-10'),
            price: 69.99,
            genre: 'First-person adventure',
            description: 'Samus Aran returns in a new first-person adventure built for Nintendo hardware.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Donkey Kong Bananza',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2025-07-17'),
            price: 69.99,
            genre: 'Platformer',
            description: 'Donkey Kong smashes through a brand-new platforming adventure packed with secrets.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Nintendo Switch 2 Welcome Tour',
            developer: 'Nintendo',
            releaseDate: new Date('2025-06-05'),
            price: 9.99,
            genre: 'Interactive demo',
            description: 'A guided interactive showcase designed to introduce the features of Nintendo Switch 2.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Pokemon Legends: Z-A',
            developer: 'Game Freak',
            releaseDate: new Date('2025-11-14'),
            price: 69.99,
            genre: 'Action role-playing',
            description: 'A new Pokemon Legends adventure set in Lumiose City with large-scale urban exploration.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Kirby Air Riders',
            developer: 'HAL Laboratory',
            releaseDate: new Date('2025-09-18'),
            price: 59.99,
            genre: 'Racing',
            description: 'Kirby returns to high-speed arcade racing with colorful tracks and chaotic multiplayer.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Hyrule Warriors: Imprisoning War',
            developer: 'Koei Tecmo',
            releaseDate: new Date('2026-03-20'),
            price: 69.99,
            genre: 'Action',
            description: 'Battle through a large-scale Musou retelling set during the ancient war of Hyrule.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Super Mario 3D All-Stars 2',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2026-02-13'),
            price: 69.99,
            genre: 'Platformer',
            description: 'A premium collection of modernized 3D Mario adventures tailored for Nintendo Switch 2.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'F-Zero GX Recharged',
            developer: 'Nintendo',
            releaseDate: new Date('2026-05-08'),
            price: 59.99,
            genre: 'Racing',
            description: 'A high-speed revival of F-Zero focused on fast tracks, sharp controls, and online competition.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Animal Crossing: New Horizons DX',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2026-04-03'),
            price: 59.99,
            genre: 'Simulation',
            description: 'A refreshed island life experience with expanded customization and enhanced online features.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Splatoon Raiders',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2026-07-24'),
            price: 59.99,
            genre: 'Third-person shooter',
            description: 'A colorful co-op spin-off that sends Inklings on high-energy missions beyond the city.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Luigis Mansion 4',
            developer: 'Next Level Games',
            releaseDate: new Date('2026-10-16'),
            price: 59.99,
            genre: 'Action-adventure',
            description: 'Luigi investigates another haunted getaway filled with puzzles, ghosts, and slapstick scares.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Mario Maker Next',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2026-08-21'),
            price: 59.99,
            genre: 'Platformer',
            description: 'Build and share even more ambitious Mario stages with new tools and creator-focused features.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Xenoblade Chronicles X Definitive Orbit',
            developer: 'Monolith Soft',
            releaseDate: new Date('2026-09-11'),
            price: 69.99,
            genre: 'Action role-playing',
            description: 'Explore a giant alien world in an expanded definitive edition of the open-world RPG adventure.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Fire Emblem Echoes of Elyos',
            developer: 'Intelligent Systems',
            releaseDate: new Date('2026-11-20'),
            price: 59.99,
            genre: 'Tactical role-playing',
            description: 'A new tactical saga with political conflict, bonded units, and large-scale battlefields.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Pikmin Explorers',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2027-03-12'),
            price: 59.99,
            genre: 'Real-time strategy',
            description: 'Lead squads of Pikmin through larger expedition zones full of hazards, caves, and treasure.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Star Fox Reignition',
            developer: 'Nintendo',
            releaseDate: new Date('2027-02-05'),
            price: 59.99,
            genre: 'Action',
            description: 'Fox McCloud returns in a fast-paced space combat revival with cinematic missions and online dogfights.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'ARMS Turbo',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2027-01-15'),
            price: 49.99,
            genre: 'Fighting',
            description: 'The stretchy fighting series gets a faster, flashier competitive sequel built for new hardware.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Captain Toad World Builder',
            developer: 'Nintendo EPD',
            releaseDate: new Date('2027-04-23'),
            price: 49.99,
            genre: 'Puzzle',
            description: 'Captain Toad returns with bigger diorama puzzles and cooperative stage-building tools.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Bayonetta 4',
            developer: 'PlatinumGames',
            releaseDate: new Date('2027-05-14'),
            price: 69.99,
            genre: 'Action',
            description: 'Bayonetta unleashes stylish demon-fueled combat in an explosive new character action sequel.',
            console_id: switch2?.id || 0,
        },
        {
            title: 'Hogwarts Legacy',
            developer: 'Avalanche Software',
            releaseDate: new Date('2023-02-10'),
            price: 59.99,
            genre: 'Action role-playing',
            description: 'Experience a new story set in the wizarding world.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Balatro',
            developer: 'LocalThunk',
            releaseDate: new Date('2024-02-20'),
            price: 14.99,
            genre: 'Roguelike deckbuilder',
            description: 'Build absurd poker hands and break the scoring system in this highly replayable deckbuilder.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Dave the Diver',
            developer: 'Mintrocket',
            releaseDate: new Date('2023-06-28'),
            price: 19.99,
            genre: 'Adventure',
            description: 'Dive for fish by day and run a sushi restaurant by night in this charming hybrid adventure.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Vampire Survivors',
            developer: 'poncle',
            releaseDate: new Date('2022-10-20'),
            price: 4.99,
            genre: 'Roguelite',
            description: 'Survive endless monster waves while stacking devastating builds in bite-sized runs.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Disco Elysium - The Final Cut',
            developer: 'ZA/UM',
            releaseDate: new Date('2021-03-30'),
            price: 39.99,
            genre: 'Role-playing',
            description: 'A deeply narrative detective RPG where your skills argue with you as much as suspects do.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Slay the Spire',
            developer: 'Mega Crit',
            releaseDate: new Date('2019-01-23'),
            price: 24.99,
            genre: 'Deckbuilding roguelike',
            description: 'Craft a unique deck, defeat bizarre enemies, and climb the spire in endlessly replayable runs.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Persona 3 Reload',
            developer: 'Atlus',
            releaseDate: new Date('2024-02-02'),
            price: 69.99,
            genre: 'Role-playing',
            description: 'A stylish modern remake of the beloved RPG with polished combat and presentation.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Sea of Stars',
            developer: 'Sabotage Studio',
            releaseDate: new Date('2023-08-29'),
            price: 34.99,
            genre: 'Role-playing',
            description: 'A turn-based RPG inspired by the 16-bit era with gorgeous pixel art and cooperative traversal.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Deep Rock Galactic: Survivor',
            developer: 'Funday Games',
            releaseDate: new Date('2024-02-14'),
            price: 9.99,
            genre: 'Auto-shooter roguelite',
            description: 'Mine, shoot, and survive alien swarms in a compact roguelite spin-off built for short sessions.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Hades II',
            developer: 'Supergiant Games',
            releaseDate: new Date('2024-05-06'),
            price: 29.99,
            genre: 'Roguelike',
            description: 'Descend into mythic battles once more in a fast-paced roguelike adventure built for repeat runs.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Brotato',
            developer: 'Blobfish',
            releaseDate: new Date('2023-06-23'),
            price: 4.99,
            genre: 'Auto-shooter',
            description: 'A compact arena shooter where quick runs and wild builds make it perfect for handheld play.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Into the Breach',
            developer: 'Subset Games',
            releaseDate: new Date('2018-02-27'),
            price: 14.99,
            genre: 'Tactical strategy',
            description: 'Control mechs in elegant turn-based battles where every move matters.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'The Binding of Isaac Rebirth',
            developer: 'Nicalis',
            releaseDate: new Date('2014-11-04'),
            price: 14.99,
            genre: 'Roguelike',
            description: 'A foundational action roguelike packed with chaotic item synergies and endless replayability.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Risk of Rain Returns',
            developer: 'Hopoo Games',
            releaseDate: new Date('2023-11-08'),
            price: 14.99,
            genre: 'Roguelike',
            description: 'The original Risk of Rain returns with polished pixel art and intense run-based action.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Monster Train',
            developer: 'Shiny Shoe',
            releaseDate: new Date('2020-05-21'),
            price: 24.99,
            genre: 'Deckbuilding roguelike',
            description: 'Defend your train across layered tactical battles in one of the sharpest deckbuilding roguelikes around.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Grim Dawn',
            developer: 'Crate Entertainment',
            releaseDate: new Date('2016-02-25'),
            price: 24.99,
            genre: 'Action role-playing',
            description: 'A deep loot-heavy action RPG with flexible class combinations and a grim fantasy setting.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Yakuza Like a Dragon',
            developer: 'Ryu Ga Gotoku Studio',
            releaseDate: new Date('2020-11-10'),
            price: 59.99,
            genre: 'Role-playing',
            description: 'Ichiban Kasuga leads a heartfelt turn-based RPG through the streets of Yokohama.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Cassette Beasts',
            developer: 'Bytten Studio',
            releaseDate: new Date('2023-04-26'),
            price: 19.99,
            genre: 'Role-playing',
            description: 'Fuse monsters and explore a vibrant world in this inventive creature-collecting RPG.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Pizza Tower',
            developer: 'Tour De Pizza',
            releaseDate: new Date('2023-01-26'),
            price: 19.99,
            genre: 'Platformer',
            description: 'A frantic hand-drawn platformer with expressive animation and relentless momentum.',
            console_id: steamDeck?.id || 0,
        },
        {
            title: 'Dredge',
            developer: 'Black Salt Games',
            releaseDate: new Date('2023-03-30'),
            price: 24.99,
            genre: 'Adventure',
            description: 'Fish by day and uncover eerie maritime mysteries by night in this atmospheric indie hit.',
            console_id: steamDeck?.id || 0,
        },

        {
    title: 'Baldur\'s Gate 3',
    developer: 'Larian Studios',
    releaseDate: new Date('2023-08-03'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'Gather your party and return to the Forgotten Realms.',
    console_id: ps5?.id || 0,
},
{
    title: 'Cyberpunk 2077',
    developer: 'CD Projekt Red',
    releaseDate: new Date('2020-12-10'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'An open-world action-adventure set in Night City.',
    console_id: ps5?.id || 0,
},
{
    title: 'Resident Evil 4 Remake',
    developer: 'Capcom',
    releaseDate: new Date('2023-03-24'),
    price: 59.99,
    genre: 'Survival horror',
    description: 'Leon Kennedy embarks on a mission to rescue the President\'s daughter.',
    console_id: ps5?.id || 0,
},
{
    title: 'Final Fantasy XVI',
    developer: 'Square Enix',
    releaseDate: new Date('2023-06-22'),
    price: 69.99,
    genre: 'Action role-playing',
    description: 'A dark fantasy epic following Clive Rosfield.',
    console_id: ps5?.id || 0,
},
{
    title: 'Horizon Forbidden West',
    developer: 'Guerrilla Games',
    releaseDate: new Date('2022-02-18'),
    price: 69.99,
    genre: 'Action-adventure',
    description: 'Aloy ventures into the Forbidden West to save the world.',
    console_id: ps5?.id || 0,
},
{
    title: 'Demon\'s Souls',
    developer: 'Bluepoint Games',
    releaseDate: new Date('2020-11-12'),
    price: 69.99,
    genre: 'Action role-playing',
    description: 'A remake of the classic PlayStation 3 game.',
    console_id: ps5?.id || 0,
},
{
    title: 'Ratchet & Clank: Rift Apart',
    developer: 'Insomniac Games',
    releaseDate: new Date('2021-06-11'),
    price: 69.99,
    genre: 'Platformer',
    description: 'Travel between dimensions with Ratchet and Clank.',
    console_id: ps5?.id || 0,
},
{
    title: 'Ghost of Tsushima',
    developer: 'Sucker Punch Productions',
    releaseDate: new Date('2020-07-17'),
    price: 59.99,
    genre: 'Action-adventure',
    description: 'Jin Sakai fights to protect Tsushima Island from Mongol invaders.',
    console_id: ps5?.id || 0,
},
{
    title: 'The Last of Us Part I',
    developer: 'Naughty Dog',
    releaseDate: new Date('2022-09-02'),
    price: 69.99,
    genre: 'Action-adventure',
    description: 'A rebuilt version of the acclaimed classic.',
    console_id: ps5?.id || 0,
},
{
    title: 'Returnal',
    developer: 'Housemarque',
    releaseDate: new Date('2021-04-30'),
    price: 69.99,
    genre: 'Roguelike',
    description: 'A third-person shooter with time-loop mechanics.',
    console_id: ps5?.id || 0,
},
{
    title: 'Alan Wake 2',
    developer: 'Remedy Entertainment',
    releaseDate: new Date('2023-10-27'),
    price: 59.99,
    genre: 'Survival horror',
    description: 'A horror story that unfolds across two realities.',
    console_id: ps5?.id || 0,
},
{
    title: 'Dead Space',
    developer: 'Motive Studio',
    releaseDate: new Date('2023-01-27'),
    price: 69.99,
    genre: 'Survival horror',
    description: 'A remake of the 2008 sci-fi horror classic.',
    console_id: ps5?.id || 0,
},
{
    title: 'Street Fighter 6',
    developer: 'Capcom',
    releaseDate: new Date('2023-06-02'),
    price: 59.99,
    genre: 'Fighting',
    description: 'The next evolution of the fighting game franchise.',
    console_id: ps5?.id || 0,
},
{
    title: 'Diablo IV',
    developer: 'Blizzard Entertainment',
    releaseDate: new Date('2023-06-06'),
    price: 69.99,
    genre: 'Action role-playing',
    description: 'Return to the dark world of Sanctuary.',
    console_id: ps5?.id || 0,
},
{
    title: 'Armored Core VI: Fires of Rubicon',
    developer: 'FromSoftware',
    releaseDate: new Date('2023-08-25'),
    price: 59.99,
    genre: 'Action',
    description: 'Mech-based combat from the creators of Elden Ring.',
    console_id: ps5?.id || 0,
},
{
    title: 'Lies of P',
    developer: 'Neowiz Games',
    releaseDate: new Date('2023-09-19'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'A dark retelling of Pinocchio in a Belle Époque world.',
    console_id: ps5?.id || 0,
},
{
    title: 'Wo Long: Fallen Dynasty',
    developer: 'Team Ninja',
    releaseDate: new Date('2023-03-03'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'A dark fantasy set in the Three Kingdoms era.',
    console_id: ps5?.id || 0,
},
{
    title: 'Star Wars Jedi: Survivor',
    developer: 'Respawn Entertainment',
    releaseDate: new Date('2023-04-28'),
    price: 69.99,
    genre: 'Action-adventure',
    description: 'Cal Kestis continues his fight against the Empire.',
    console_id: ps5?.id || 0,
},
{
    title: 'Final Fantasy VII Rebirth',
    developer: 'Square Enix',
    releaseDate: new Date('2024-02-29'),
    price: 69.99,
    genre: 'Action role-playing',
    description: 'The second installment in the Final Fantasy VII remake project.',
    console_id: ps5?.id || 0,
},
{
    title: 'Helldivers 2',
    developer: 'Arrowhead Game Studios',
    releaseDate: new Date('2024-02-08'),
    price: 39.99,
    genre: 'Third-person shooter',
    description: 'Fight for democracy in co-op galactic warfare.',
    console_id: ps5?.id || 0,
},
{
    title: 'Forza Motorsport',
    developer: 'Turn 10 Studios',
    releaseDate: new Date('2023-10-10'),
    price: 69.99,
    genre: 'Racing',
    description: 'The ultimate racing simulation experience.',
    console_id: xbox?.id || 0,
},
{
    title: 'Microsoft Flight Simulator',
    developer: 'Asobo Studio',
    releaseDate: new Date('2020-08-18'),
    price: 59.99,
    genre: 'Simulation',
    description: 'Fly anywhere in the world with realistic graphics.',
    console_id: xbox?.id || 0,
},
{
    title: 'Psychonauts 2',
    developer: 'Double Fine Productions',
    releaseDate: new Date('2021-08-25'),
    price: 59.99,
    genre: 'Platformer',
    description: 'Raz embarks on a mind-bending adventure.',
    console_id: xbox?.id || 0,
},
{
    title: 'Hi-Fi Rush',
    developer: 'Tango Gameworks',
    releaseDate: new Date('2023-01-25'),
    price: 29.99,
    genre: 'Rhythm action',
    description: 'A rhythm-action game where everything moves to the beat.',
    console_id: xbox?.id || 0,
},
{
    title: 'Age of Empires IV',
    developer: 'Relic Entertainment',
    releaseDate: new Date('2021-10-28'),
    price: 59.99,
    genre: 'Real-time strategy',
    description: 'Build and conquer throughout the ages.',
    console_id: xbox?.id || 0,
},
{
    title: 'Grounded',
    developer: 'Obsidian Entertainment',
    releaseDate: new Date('2022-09-27'),
    price: 39.99,
    genre: 'Survival',
    description: 'Survive as a shrunken child in a backyard.',
    console_id: xbox?.id || 0,
},
{
    title: 'Pentiment',
    developer: 'Obsidian Entertainment',
    releaseDate: new Date('2022-11-15'),
    price: 19.99,
    genre: 'Adventure',
    description: 'A narrative-driven mystery set in 16th century Germany.',
    console_id: xbox?.id || 0,
},
{
    title: 'Redfall',
    developer: 'Arkane Studios',
    releaseDate: new Date('2023-05-02'),
    price: 69.99,
    genre: 'First-person shooter',
    description: 'Open-world co-op vampire hunting.',
    console_id: xbox?.id || 0,
},
{
    title: 'Halo: The Master Chief Collection',
    developer: '343 Industries',
    releaseDate: new Date('2019-12-03'),
    price: 39.99,
    genre: 'First-person shooter',
    description: 'Six Halo games in one collection.',
    console_id: xbox?.id || 0,
},
{
    title: 'Gears 5',
    developer: 'The Coalition',
    releaseDate: new Date('2019-09-10'),
    price: 59.99,
    genre: 'Third-person shooter',
    description: 'The latest installment in the Gears of War saga.',
    console_id: xbox?.id || 0,
},
{
    title: 'Ori and the Will of the Wisps',
    developer: 'Moon Studios',
    releaseDate: new Date('2020-03-11'),
    price: 29.99,
    genre: 'Platformer',
    description: 'A beautiful action-platformer with emotional storytelling.',
    console_id: xbox?.id || 0,
},
{
    title: 'Sea of Thieves',
    developer: 'Rare',
    releaseDate: new Date('2018-03-20'),
    price: 39.99,
    genre: 'Adventure',
    description: 'Pirate adventure on the high seas.',
    console_id: xbox?.id || 0,
},
{
    title: 'State of Decay 2',
    developer: 'Undead Labs',
    releaseDate: new Date('2018-05-22'),
    price: 29.99,
    genre: 'Survival',
    description: 'Survive the zombie apocalypse with your community.',
    console_id: xbox?.id || 0,
},
{
    title: 'Sunset Overdrive',
    developer: 'Insomniac Games',
    releaseDate: new Date('2014-10-28'),
    price: 19.99,
    genre: 'Action-adventure',
    description: 'Open-world mayhem with style and humor.',
    console_id: xbox?.id || 0,
},
{
    title: 'Quantum Break',
    developer: 'Remedy Entertainment',
    releaseDate: new Date('2016-04-05'),
    price: 39.99,
    genre: 'Action-adventure',
    description: 'A narrative-driven game with time manipulation.',
    console_id: xbox?.id || 0,
},
{
    title: 'Super Mario Odyssey',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2017-10-27'),
    price: 59.99,
    genre: 'Platformer',
    description: 'Mario explores new worlds with his companion Cappy.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Super Mario Bros. Wonder',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2023-10-20'),
    price: 59.99,
    genre: 'Platformer',
    description: 'A new 2D Mario adventure with Wonder Flowers.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'The Legend of Zelda: Breath of the Wild',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2017-03-03'),
    price: 59.99,
    genre: 'Action-adventure',
    description: 'Link awakens in a vast open-world Hyrule.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Metroid Dread',
    developer: 'MercurySteam',
    releaseDate: new Date('2021-10-08'),
    price: 59.99,
    genre: 'Action-adventure',
    description: 'Samus Aran faces a new threat on Planet ZDR.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Metroid Prime Remastered',
    developer: 'Retro Studios',
    releaseDate: new Date('2023-02-08'),
    price: 39.99,
    genre: 'First-person adventure',
    description: 'A remaster of the GameCube classic.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Super Smash Bros. Ultimate',
    developer: 'Bandai Namco Studios',
    releaseDate: new Date('2018-12-07'),
    price: 59.99,
    genre: 'Fighting',
    description: 'The ultimate crossover fighting game.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Mario Kart 8 Deluxe',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2017-04-28'),
    price: 59.99,
    genre: 'Racing',
    description: 'The definitive Mario Kart experience.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Animal Crossing: New Horizons',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2020-03-20'),
    price: 59.99,
    genre: 'Simulation',
    description: 'Build your dream island paradise.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Fire Emblem: Three Houses',
    developer: 'Intelligent Systems',
    releaseDate: new Date('2019-07-26'),
    price: 59.99,
    genre: 'Tactical role-playing',
    description: 'Lead a house at the Officers Academy.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Fire Emblem Engage',
    developer: 'Intelligent Systems',
    releaseDate: new Date('2023-01-20'),
    price: 59.99,
    genre: 'Tactical role-playing',
    description: 'Summon heroes from past Fire Emblem games.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Xenoblade Chronicles 3',
    developer: 'Monolith Soft',
    releaseDate: new Date('2022-07-29'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'The epic conclusion to the Xenoblade trilogy.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Xenoblade Chronicles: Definitive Edition',
    developer: 'Monolith Soft',
    releaseDate: new Date('2020-05-29'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'The remastered version of the RPG classic.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Splatoon 3',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2022-09-09'),
    price: 59.99,
    genre: 'Third-person shooter',
    description: 'Turf Wars return with new weapons and modes.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Kirby and the Forgotten Land',
    developer: 'HAL Laboratory',
    releaseDate: new Date('2022-03-25'),
    price: 59.99,
    genre: 'Platformer',
    description: 'Kirby in a post-apocalyptic 3D world.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Luigi\'s Mansion 3',
    developer: 'Next Level Games',
    releaseDate: new Date('2019-10-31'),
    price: 59.99,
    genre: 'Action-adventure',
    description: 'Luigi explores a haunted hotel.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Pikmin 4',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2023-07-21'),
    price: 59.99,
    genre: 'Real-time strategy',
    description: 'Command Pikmin to explore a mysterious planet.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Bayonetta 3',
    developer: 'PlatinumGames',
    releaseDate: new Date('2022-10-28'),
    price: 59.99,
    genre: 'Action',
    description: 'The witch returns with demon summoning powers.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Astral Chain',
    developer: 'PlatinumGames',
    releaseDate: new Date('2019-08-30'),
    price: 59.99,
    genre: 'Action',
    description: 'Control two characters simultaneously.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Octopath Traveler II',
    developer: 'Square Enix',
    releaseDate: new Date('2023-02-24'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'A new HD-2D RPG with eight protagonists.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Triangle Strategy',
    developer: 'Artdink',
    releaseDate: new Date('2022-03-04'),
    price: 59.99,
    genre: 'Tactical role-playing',
    description: 'Choices determine the fate of three nations.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Live A Live',
    developer: 'Square Enix',
    releaseDate: new Date('2022-07-22'),
    price: 49.99,
    genre: 'Role-playing',
    description: 'A remake of the classic RPG with HD-2D graphics.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Advance Wars 1+2: Re-Boot Camp',
    developer: 'WayForward',
    releaseDate: new Date('2023-04-21'),
    price: 59.99,
    genre: 'Tactical strategy',
    description: 'Remakes of the classic GBA strategy games.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Mario + Rabbids: Sparks of Hope',
    developer: 'Ubisoft Milan',
    releaseDate: new Date('2022-10-20'),
    price: 59.99,
    genre: 'Tactical role-playing',
    description: 'A new strategy adventure in space.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Persona 5 Royal',
    developer: 'Atlus',
    releaseDate: new Date('2022-10-21'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'The definitive version of the acclaimed RPG.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Shin Megami Tensei V',
    developer: 'Atlus',
    releaseDate: new Date('2021-11-12'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'Explore a post-apocalyptic Tokyo.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Dragon Quest XI S: Echoes of an Elusive Age',
    developer: 'Square Enix',
    releaseDate: new Date('2019-09-27'),
    price: 49.99,
    genre: 'Role-playing',
    description: 'The definitive edition of the beloved RPG.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Monster Hunter Rise',
    developer: 'Capcom',
    releaseDate: new Date('2021-03-26'),
    price: 39.99,
    genre: 'Action role-playing',
    description: 'Hunt monsters in a new Japanese-inspired setting.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Monster Hunter Stories 2: Wings of Ruin',
    developer: 'Capcom',
    releaseDate: new Date('2021-07-09'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'A monster-taming RPG in the Monster Hunter universe.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Bravely Default II',
    developer: 'Claytechworks',
    releaseDate: new Date('2021-02-26'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'A classic-style RPG with unique job system.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Paper Mario: The Origami King',
    developer: 'Intelligent Systems',
    releaseDate: new Date('2020-07-17'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'Mario saves the world from origami invaders.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Yoshi\'s Crafted World',
    developer: 'Good-Feel',
    releaseDate: new Date('2019-03-29'),
    price: 59.99,
    genre: 'Platformer',
    description: 'Yoshi in a handmade craft world.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Donkey Kong Country: Tropical Freeze',
    developer: 'Retro Studios',
    releaseDate: new Date('2018-05-04'),
    price: 59.99,
    genre: 'Platformer',
    description: 'Donkey Kong returns with classic platforming.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Captain Toad: Treasure Tracker',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2018-07-13'),
    price: 39.99,
    genre: 'Puzzle',
    description: 'Solve puzzles in diorama-style levels.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Cadence of Hyrule',
    developer: 'Brace Yourself Games',
    releaseDate: new Date('2019-06-13'),
    price: 24.99,
    genre: 'Rhythm adventure',
    description: 'A Zelda rhythm game in the Crypt of the NecroDancer style.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Hyrule Warriors: Age of Calamity',
    developer: 'Koei Tecmo',
    releaseDate: new Date('2020-11-20'),
    price: 59.99,
    genre: 'Action',
    description: 'A prequel to Breath of the Wild.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Pokémon Legends: Arceus',
    developer: 'Game Freak',
    releaseDate: new Date('2022-01-28'),
    price: 59.99,
    genre: 'Action role-playing',
    description: 'A new take on Pokémon in feudal Sinnoh.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Pokémon Brilliant Diamond',
    developer: 'ILCA',
    releaseDate: new Date('2021-11-19'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'Remakes of the Sinnoh region classics.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Pokémon Violet',
    developer: 'Game Freak',
    releaseDate: new Date('2022-11-18'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'The open-world Pokémon adventure in Paldea.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'New Pokémon Snap',
    developer: 'Bandai Namco Studios',
    releaseDate: new Date('2021-04-30'),
    price: 59.99,
    genre: 'Photography',
    description: 'Photograph Pokémon in their natural habitats.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Pokémon Mystery Dungeon: Rescue Team DX',
    developer: 'Spike Chunsoft',
    releaseDate: new Date('2020-03-06'),
    price: 59.99,
    genre: 'Role-playing',
    description: 'A remake of the classic Pokémon Mystery Dungeon.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Ring Fit Adventure',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2019-10-18'),
    price: 79.99,
    genre: 'Fitness',
    description: 'An adventure game that uses exercise to progress.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Nintendo Switch Sports',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2022-04-29'),
    price: 39.99,
    genre: 'Sports',
    description: 'Play sports with motion controls.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Mario Strikers: Battle League',
    developer: 'Next Level Games',
    releaseDate: new Date('2022-06-10'),
    price: 59.99,
    genre: 'Sports',
    description: 'Intense 5v5 soccer with Mario characters.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Mario Golf: Super Rush',
    developer: 'Camelot',
    releaseDate: new Date('2021-06-25'),
    price: 59.99,
    genre: 'Sports',
    description: 'Arcade-style golf with speed mode.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Mario Tennis Aces',
    developer: 'Camelot',
    releaseDate: new Date('2018-06-22'),
    price: 59.99,
    genre: 'Sports',
    description: 'Tennis with special shots and abilities.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'WarioWare: Get It Together!',
    developer: 'Intelligent Systems',
    releaseDate: new Date('2021-09-10'),
    price: 49.99,
    genre: 'Party',
    description: 'Microgame collection with playable characters.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Clubhouse Games: 51 Worldwide Classics',
    developer: 'Nintendo EPD',
    releaseDate: new Date('2020-06-05'),
    price: 39.99,
    genre: 'Party',
    description: 'Collection of classic board and card games.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Hades',
    developer: 'Supergiant Games',
    releaseDate: new Date('2020-09-17'),
    price: 24.99,
    genre: 'Roguelike',
    description: 'Escape from the Underworld in this acclaimed roguelike.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Stardew Valley',
    developer: 'ConcernedApe',
    releaseDate: new Date('2017-10-05'),
    price: 14.99,
    genre: 'Simulation',
    description: 'Farm, mine, and build relationships.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Hollow Knight',
    developer: 'Team Cherry',
    releaseDate: new Date('2018-06-12'),
    price: 15.99,
    genre: 'Metroidvania',
    description: 'Explore the vast kingdom of Hallownest.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Celeste',
    developer: 'Extremely OK Games',
    releaseDate: new Date('2018-01-25'),
    price: 19.99,
    genre: 'Platformer',
    description: 'A challenging platformer about climbing a mountain.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Cuphead',
    developer: 'Studio MDHR',
    releaseDate: new Date('2019-04-18'),
    price: 19.99,
    genre: 'Action',
    description: 'Run-and-gun with 1930s cartoon style.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Undertale',
    developer: 'Toby Fox',
    releaseDate: new Date('2018-09-15'),
    price: 14.99,
    genre: 'Role-playing',
    description: 'An RPG where nobody has to die.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Deltarune',
    developer: 'Toby Fox',
    releaseDate: new Date('2019-02-28'),
    price: 0,
    genre: 'Role-playing',
    description: 'A new adventure from the creator of Undertale.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Among Us',
    developer: 'Innersloth',
    releaseDate: new Date('2020-12-15'),
    price: 4.99,
    genre: 'Party',
    description: 'Social deduction game in space.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Fall Guys',
    developer: 'Mediatonic',
    releaseDate: new Date('2022-06-21'),
    price: 0,
    genre: 'Party',
    description: 'Battle royale with obstacle courses.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Overcooked! 2',
    developer: 'Ghost Town Games',
    releaseDate: new Date('2018-08-07'),
    price: 24.99,
    genre: 'Party',
    description: 'Co-op cooking chaos.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Untitled Goose Game',
    developer: 'House House',
    releaseDate: new Date('2019-09-20'),
    price: 19.99,
    genre: 'Puzzle',
    description: 'A mischievous goose causes havoc in a village.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Katana Zero',
    developer: 'Askiisoft',
    releaseDate: new Date('2019-04-18'),
    price: 14.99,
    genre: 'Action',
    description: 'Neon-noir action with time manipulation.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Dead Cells',
    developer: 'Motion Twin',
    releaseDate: new Date('2018-08-07'),
    price: 24.99,
    genre: 'Roguelike',
    description: 'Action-platformer with permadeath.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Ori and the Blind Forest',
    developer: 'Moon Studios',
    releaseDate: new Date('2019-09-27'),
    price: 19.99,
    genre: 'Platformer',
    description: 'A beautiful metroidvania about a lost guardian.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Okami HD',
    developer: 'Clover Studio',
    releaseDate: new Date('2018-08-09'),
    price: 19.99,
    genre: 'Action-adventure',
    description: 'The classic adventure with celestial brush mechanics.',
    console_id: switchOLED?.id || 0,
},
{
    title: 'Ni no Kuni: Wrath of the White Witch',
    developer: 'Level-5',
    releaseDate: new Date('2019-09-20'),
    price: 49.99,
    genre: 'Role-playing',
    description: 'Studio Ghibli collaboration RPG.',
    console_id: switchOLED?.id || 0,
}
    ]

    for (const game of gamesData) {
        if (!game.console_id) continue

        await prisma.games.create({
            data: game,
        })
    }

    console.log('🕹️ 10 games seeded')
    console.log('✅ Seed completed successfully')
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
