import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { CryptoPolyfill } from "./crypto-polyfill";
import { AppProviders } from "./providers";
import CyberpunkParticles from "@/components/CyberpunkParticles";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} cyberpunk-bg antialiased`}
      >
        <CryptoPolyfill />
        <CyberpunkParticles />
        <AppProviders>
          <div className="app-shell">{children}</div>
        </AppProviders>
      </body>
    </html>
  );
}
